[workspace]
members = ["visqol-rs", "visqol"]

[patch.crates-io]
ffsvm = { git  = "https://github.com/dstrub18/ffsvm-rust"}
simd_aligned = { git = "https://github.com/dstrub18/simd_aligned_rust"}

[profile.release]
opt-level = 3
strip = "symbols"
debug = false
lto = "fat"